spring.application.name=fruit_shop_backend
spring.profiles.active=dev
# MyBatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
#mybatis.type-aliases-package=kr.co.cofile.fruitshop.backend.dto