spring.application.name=fruit-shop-backend
spring.profiles.active=dev
# MyBatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=kr.co.cofile.fruitshop.backend.dto
mybatis.type-handlers-package=kr.co.cofile.fruitshop.backend.enums
# 리소스 버전 관리
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**