CREATE TABLE UPLOADED_FILES (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL COMMENT '업로더 사용자 ID',
	original_name VARCHAR(255) NOT NULL,
	stored_name VARCHAR(255) NOT NULL,
	file_size BIGINT NOT NULL,
	file_path VARCHAR(500) NOT NULL,
	uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);